import type { Address } from "../../core/types/address.ts";

/**
 * The number of levels in the stack of the original CHIP-8
 * implementation.
 */
export const DEFAULT_STACK_CAPACITY = 16;

/**
 * Represents the CHIP-8 call stack.
 *
 * The stack stores return addresses generated by subroutine calls.
 *
 * @remarks
 * The stack deliberately encapsulates its storage and stack pointer.
 * Consumers should use the stack operations rather than manipulating an
 * array or stack pointer directly. This keeps stack invariants in one place
 * and allows the underlying representation to change without affecting
 * the CPU.
 */
export class Stack {
  private readonly values: Address[] = [];
  private readonly capacity: number;
  /**
   * Creates a new stack.
   *
   * @param capacity - Maximum number of addresses that can be stored.
   *
   * @throws {RangeError}
   * If `capacity` is not a positive integer.
   */
  public constructor(capacity: number = DEFAULT_STACK_CAPACITY) {
    if (!Number.isInteger(capacity) || capacity <= 0) {
      throw new RangeError(`Stack capacity must be a positive integer: ${capacity}`);
    }

    this.capacity = capacity;
  }

  /**
   * Adds an address to the top of the stack.
   *
   * @param address - Address to store.
   *
   * @throws {RangeError}
   * If the stack is already full.
   */
  public push(address: Address): void {
    if (this.isFull()) {
      throw new RangeError("Cannot push to a full stack.");
    }

    this.values.push(address);
  }

  /**
   * Removes and returns the address at the top of the stack.
   *
   * @returns The address at the top of the stack.
   *
   * @throws {RangeError}
   * If the stack is empty.
   */
  public pop(): Address {
    if (this.isEmpty()) {
      throw new RangeError("Cannot pop from an empty stack.");
    }

    return this.values.pop()!;
  }

  /**
   * Returns the address at the top of the stack without removing it.
   *
   * @returns The address at the top of the stack.
   *
   * @throws {RangeError}
   * If the stack is empty.
   */
  public peek(): Address {
    if (this.isEmpty()) {
      throw new RangeError("Cannot peek at an empty stack.");
    }

    return this.values[this.values.length - 1];
  }

  /**
   * Returns the number of addresses currently stored in the stack.
   */
  public getSize(): number {
    return this.values.length;
  }

  /**
   * Returns the maximum number of addresses the stack can contain.
   */
  public getCapacity(): number {
    return this.capacity;
  }

  /**
   * Determines whether the stack contains no addresses.
   */
  public isEmpty(): boolean {
    return this.values.length === 0;
  }

  /**
   * Determines whether the stack has reached its maximum capacity.
   */
  public isFull(): boolean {
    return this.values.length >= this.capacity;
  }

  /**
   * Returns a copy of the current stack contents.
   *
   * @remarks
   * The returned array is independent of the live stack. Changes to the
   * stack after this method returns therefore cannot modify the snapshot.
   *
   * This is useful for debugging and state inspection.
   */
  public snapshot(): readonly Address[] {
    return [...this.values];
  }
}
